### ISSUE TITLE
feature request: explanation of git-id

### ISSUE THREAD

**Issue by Tux** [abeltje/Test-Smoke#23]
When you go to http://perl5.test-smoke.org/search, one of the columns 
presented is "Git-id".  Its contents look like this:

v5.25.8-269-g01f9673
v5.25.8-196-g3626fc2
v5.25.8-208-g05053e2
v5.25.8-260-g57b3a6b6ec

What these strings mean is not entirely self-evident.  I can infer that 
'v5.25.8' means "after we've released perl-5.25.8."  And I understand 
that in the final part of the string, everything after the initial 'g' 
is a git SHA (commit ID).

But I've never understood what the middle integer is supposed to mean. 
Those integers do not appear to be assigned in strictly increasing 
numerical order.  It would be nice if there was some explanation on the 
page as to what that part and the whole Git-id are supposed to mean.

Thank you very much.
Jim Keenan

**Comment by abeltje** [comment]
git help describe
