### ISSUE TITLE
feature request: order by column

### ISSUE THREAD

**Issue by Tux** [abeltje/Test-Smoke#24]
When you go to http://perl5.test-smoke.org/search, you see a table whose 
columns are these:

Arch	Host	OS	Git-id	Smoke date	Status

AFAICT, you have no ability to select the way the rows in the table are 
ordered.  It appears that the sorting is done on the columns in 
left-to-right order, each column ascending.

I find myself wishing that I could have the records for individual 
reports return sorted either by Git-id ASC or by "Smoke date" DESC.

Thank you very much.
Jim Keenan

**Comment by abeltje** [comment]
I 'm looking for a way to move this issue to the https://github.com/abeltje/CoreSmokeDB repository

**Comment by abeltje** [comment]
@jkeenan I have moved this issue to the CoreSmokeDB repository...
