### ISSUE TITLE
Add "Branch" column to display results

### ISSUE THREAD

**Issue by jkeenan** [abeltje/Test-Smoke#35]
The table at http://perl5.test-smoke.org/search currently reports these 6 columns:
```
Arch	Host	OS	Git-id	Smoke date	Status
```
We (well, some of us) in Perl 5 Porters would like to encourage more smoke-testing of branches.  If that were to happen, I'd like to be able to easily distinguish between blead and non-blead branches.

How feasible would it be to add a **Branch** column?

Or, alternatively, to permit a user to customize the display by, say, swapping out **Git-id** in favor of **Branch**?

Thank you very much.
Jim Keenan

**Comment by abeltje** [comment]
Please create issues in the correct repository as I cannot move them around: https://github.com/abeltje/CoreSmokeDB/issues/6
